"""empty message

Revision ID: 00d77b0b21e4
Revises: 37241aa1020d
Create Date: 2018-02-01 12:42:45.530000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d77b0b21e4'
down_revision = '37241aa1020d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idc_asset_inventory',
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('idc', sa.Integer(), nullable=True),
    sa.Column('cabinet', sa.String(length=20), nullable=True),
    sa.Column('addresses', sa.Integer(), nullable=True),
    sa.Column('host_name', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('asset_code', sa.String(length=20), nullable=True),
    sa.Column('asset_sn', sa.String(length=20), nullable=True),
    sa.Column('ip_business_code', sa.String(length=50), nullable=True),
    sa.Column('ip_admin', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('interfac_person', sa.String(length=10), nullable=True),
    sa.Column('project', sa.String(length=50), nullable=True),
    sa.Column('project_contract', sa.String(length=20), nullable=True),
    sa.Column('project_acceptance_time', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('off_shelf_evaluation', sa.Integer(), nullable=True),
    sa.Column('cpu_config', sa.String(length=50), nullable=True),
    sa.Column('memory_config', sa.String(length=50), nullable=True),
    sa.Column('disk_config', sa.String(length=50), nullable=True),
    sa.Column('cpu_use_rate', sa.Integer(), nullable=True),
    sa.Column('memory_use_rate', sa.Integer(), nullable=True),
    sa.Column('disk_use_rate', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('serial_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idc_asset_inventory')
    # ### end Alembic commands ###
