"""empty message

Revision ID: 37241aa1020d
Revises: 
Create Date: 2018-02-01 11:10:21.323000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37241aa1020d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idc_asset_inventory_user',
    sa.Column('dgdh', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('dgdh'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idc_asset_inventory_user')
    # ### end Alembic commands ###
